# Generated by Django 5.1.7 on 2025-03-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='resumes/')),
                ('job_category', models.CharField(choices=[('ACCOUNTANT', 'Accountant'), ('ADVOCATE', 'Advocate'), ('AGRICULTURE', 'Agriculture'), ('APPAREL', 'Apparel'), ('ARTS', 'Arts'), ('AUTOMOBILE', 'Automobile'), ('AVIATION', 'Aviation'), ('BANKING', 'Banking'), ('BPO', 'BPO'), ('BUSINESS-DEVELOPMENT', 'Business Development'), ('CHEF', 'Chef'), ('CONSTRUCTION', 'Construction'), ('CONSULTANT', 'Consultant'), ('DESIGNER', 'Designer'), ('DIGITAL-MEDIA', 'Digital Media'), ('ENGINEERING', 'Engineering'), ('FINANCE', 'Finance'), ('FITNESS', 'Fitness'), ('HEALTHCARE', 'Healthcare'), ('HR', 'HR'), ('INFORMATION-TECHNOLOGY', 'Information Technology'), ('PUBLIC-RELATIONS', 'Public Relations'), ('SALES', 'Sales'), ('TEACHER', 'Teacher')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('skill_score', models.IntegerField(default=0)),
                ('collaboration_score', models.IntegerField(default=0)),
                ('adaptability_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='screening.resume')),
            ],
        ),
    ]
